version: "3.1"

services:
  code-survival-postgres:
    container_name: "code-survival-postgres"
    image: postgres
    restart: unless-stopped
    env_file:
      - ./application.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data