version: "3.1"

services:
  code-survival-api:
    container_name: code-survival-api
    restart: unless-stopped
    image: codesurvival/api
    depends_on:
      - code-survival-postgres
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./application.env
    ports:
      - 8081:8081

  code-survival-postgres:
    container_name: "code-survival-postgres"
    image: postgres
    user: postgres
    restart: unless-stopped
    env_file:
      - ./application.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
      - 5672:5672
      - 15672:15672