version: "3.9"

services:
  code-survival-api:
    container_name: code-survival-api
    restart: unless-stopped
    image: codesurvival/api
    depends_on:
      - code-survival-postgres
      - kotlin-compiler
    working_dir: /app
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./application.env
      - ./.env
    ports:
      - 8081:8081
    networks:
      - setted-network

  code-survival-postgres:
    container_name: "code-survival-postgres"
    image: postgres
    user: postgres
    restart: unless-stopped
    env_file:
      - ./application.env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - setted-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - setted-network
      - rabbitmq_go_net

  kotlin-compiler:
    container_name: kotlin-compiler
    image: kotlin-compiler/api
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - setted-network

networks:
  setted-network:
    name: setted-network
  rabbitmq_go_net:
      driver: bridge